classes:
  # - name: airplane
  #   ref: "02691156"
  - name: bench
    ref: "02828884"
  - name: car
    ref: "02958343"
  - name: chair
    ref: "03001627"
  # - name: lamp
  #   ref: "03636649"
  # - name: sofa
  #   ref: "04256520"
  # - name: table
  #   ref: "04379243"
